// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9RdmjZGfenpEULXx1MI8RoO1Zk6KMKi0',
    appId: '1:470342203389:android:d1572c9a7778e3abfe0b94',
    messagingSenderId: '470342203389',
    projectId: 'e-commerce-app-169b2',
    storageBucket: 'e-commerce-app-169b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQiRJcJYQovP1hPdzKe4-KJxZRRZN0MkI',
    appId: '1:470342203389:ios:18336c7b199fce7bfe0b94',
    messagingSenderId: '470342203389',
    projectId: 'e-commerce-app-169b2',
    storageBucket: 'e-commerce-app-169b2.firebasestorage.app',
    androidClientId: '470342203389-2c182grbirdmmlvvcsqm7vsk20fmpbak.apps.googleusercontent.com',
    iosClientId: '470342203389-egns5en3jpsest3iplud9iugpfaa60e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

}